soft_hand:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  hand_synergy_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: soft_hand_synergy_joint

   # Trajectory Controllers ---------------------------------------
  hand_synergy_joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - soft_hand_synergy_joint