soft_hand:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Position Controllers ---------------------------------------
  hand_synergy_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: soft_hand_synergy_joint
    pid: {p: 1.0, i: 0.1, d: 0.5}

   # Trajectory Controllers ---------------------------------------
  hand_synergy_joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - soft_hand_synergy_joint

    gains:
      soft_hand_synergy_joint: {p: 1,  d: 0.1, i: 0.5, i_clamp: 1}