# HAND CONTROLLERS

right_hand:

  # Joint State Controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Joint Trajectory Controller
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - right_hand_synergy_joint

  # Velocity Controller
  velocity_controller:
    type: soft_hand_controllers/VelocityController
    joint: right_hand_synergy_joint